module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    button_backplate: require('./buttonbackplate'),
    choc: require('./choc'),
    choc_backplate: require('./chocbackplate'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    diode_backplate: require('./diodebackplate'),
    jstph: require('./jstph'),
    jstph_backplate: require('./jstphbackplate'),
    jumper: require('./jumper'),
    mountinghole: require('./mountinghole'),
    mx: require('./mx'),
    oled: require('./oled'),
    oled_backplate: require('./oledbackplate'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro'),
    promicro_backplate: require('./promicrobackplate'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),
}